# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Felt < Formula
  desc "DAG-native task tracker. Markdown files with dependencies."
  homepage "https://github.com/cailmdaley/felt"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cailmdaley/felt/releases/download/v1.0.9/felt_Darwin_x86_64.tar.gz"
      sha256 "49dda799ddaf8527a297e29541fbb06f00bced8857b58626d2aec8bdc6d4d1c2"

      define_method(:install) do
        bin.install "felt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cailmdaley/felt/releases/download/v1.0.9/felt_Darwin_arm64.tar.gz"
      sha256 "032a44143f4f3c567e197a2c1e7f3e95f6600a5405bbcac551dd12235195bb55"

      define_method(:install) do
        bin.install "felt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cailmdaley/felt/releases/download/v1.0.9/felt_Linux_x86_64.tar.gz"
      sha256 "8229d4faab8fd32975ca5785da212d64486ad316c2114848817d4886217ee8c4"
      define_method(:install) do
        bin.install "felt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cailmdaley/felt/releases/download/v1.0.9/felt_Linux_arm64.tar.gz"
      sha256 "276893bc8ca701d61e12518807e3865cc42a8a354d89baafb653c508573f6822"
      define_method(:install) do
        bin.install "felt"
      end
    end
  end

  def post_install
    if which("claude")
      system "#{bin}/felt", "setup", "claude"
    end
    # Only re-run `felt setup codex` for users who already have Codex
    # integration installed — never silently install Codex hooks for
    # users who didn't ask for them. The detection mirrors the binary's
    # own feltCodexInstalled(): plugin entry in config.toml (1.0.8+) or
    # legacy session.sh reference in hooks.json (pre-1.0.8).
    codex_config = "#{ENV["HOME"]}/.codex/config.toml"
    codex_hooks = "#{ENV["HOME"]}/.codex/hooks.json"
    # TOML quotes keys with single or double quotes depending on the
    # writer; substring-match the plugin ref instead of the full header
    # so either form is detected.
    codex_installed = (File.exist?(codex_config) && File.read(codex_config).include?("felt@cailmdaley-felt")) ||
                     (File.exist?(codex_hooks) && File.read(codex_hooks).include?("/hooks/session.sh"))
    if codex_installed && which("codex")
      system "#{bin}/felt", "setup", "codex"
    end
  end

  test do
    system "#{bin}/felt", "--help"
  end
end
