# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Felt < Formula
  desc "DAG-native task tracker. Markdown files with dependencies."
  homepage "https://github.com/cailmdaley/felt"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cailmdaley/felt/releases/download/v0.7.0/felt_Darwin_x86_64.tar.gz"
      sha256 "28486c3820ad41c4e0346d3108764fb71ee3234655021779978f4bb85c830f9f"

      define_method(:install) do
        bin.install "felt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cailmdaley/felt/releases/download/v0.7.0/felt_Darwin_arm64.tar.gz"
      sha256 "a9470c2afd8051573117150d95bbf03183d19bff2d1d06c02dad51d7be57858f"

      define_method(:install) do
        bin.install "felt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cailmdaley/felt/releases/download/v0.7.0/felt_Linux_x86_64.tar.gz"
      sha256 "b2f844e833a3e63a2f65bd4146b0c7e9ba4967e5a414e9ff4b3f4345ff2494d0"
      define_method(:install) do
        bin.install "felt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cailmdaley/felt/releases/download/v0.7.0/felt_Linux_arm64.tar.gz"
      sha256 "6e2fbb87befcd20b7baf04b3758fcb9107231ca462f24fb3bd09a8f8fa0f13f7"
      define_method(:install) do
        bin.install "felt"
      end
    end
  end

  test do
    system "#{bin}/felt", "--help"
  end
end
